# Server
server.port=8080

# AWS Configuration
aws.region=us-east-1
aws.s3.bucket=guias-transporte-empresa-unico

# EFS Mount Path (dentro del contenedor)
efs.mount.path=/app/efs/guias_tmp

# Logging
logging.level.com.transporte.guias=DEBUG
logging.level.software.amazon.awssdk=WARN